### ISSUE TITLE
Setup: invalid json response

### ISSUE THREAD

**Issue by roybarber** [stefanjudis/netlify-menubar#2]
Getting the following when running npm run dev

````
➜  netlify-menubar git:(master) npm run dev

> netlify-menubar@1.0.0 dev /Applications/MAMP/htdocs/netlify-menubar
> electron index.js

Updating UI...
{ FetchError: invalid json response body at https://api.netlify.com/api/v1/sites/ reason: Unexpected end of JSON input
    at /Applications/MAMP/htdocs/netlify-menubar/node_modules/node-fetch/lib/index.js:241:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://api.netlify.com/api/v1/sites/ reason: Unexpected end of JSON input',
  type: 'invalid-json' }
(node:23595) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at update (/Applications/MAMP/htdocs/netlify-menubar/index.js:86:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

Screen for private token popped up and submitted.

**Comment by stefanjudis** [comment]
Hey Roy,

thanks for giving it a shot... It's very work in progress as you see. I'm almost sure that's an auth error.

The settings are stored in `~/Library/Application Support/Electron/Settings`. What happens right now is that in the auth dialog that there is a "double paste" which invalidates the token. Could you have a look at the stored token and confirm?

I'll create issues for better error handling and fixing this bug then later. :)

**Comment by roybarber** [comment]
Certainly is a double token error! 
````
{"accessToken":"XXXXXXXXXXX XXXXXXXXXXX"}
````
Now got the UI displaying, will have a play around with it :) Thanks! Great work!

**Comment by stefanjudis** [comment]
FYI I just pushed an update so that it at least shows when something is wrong with the token. :)

**Comment by stefanjudis** [comment]
There you go. :)
